# Basic
title: LIFE OF LIAN
subtitle:  苏联 | 探索未知
welcome_message:
description: 嗨，我是连书敏(@imlian)，一名来自中国的iOS攻城狮。酷爱潜水、旅行。
creator: <a href="http://imlian.com”>@lianshumin</a>

url: "http://imlian.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge 

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty. 
cover_color: blue
 
# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 晴子日语, url: 'https://itunes.apple.com/cn/app/晴子日语-自学日语的非凡搭档/id1173193999'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: imlian
    # duoshuo: 
    
# Social
social:
    weibo: mrcccp
    github: lianshumin
    twitter: lianshumin
    gplus: 101698577363756110244
    mail: 3073303@qq.com

# Google Analytics
ga:
    # id: UA-74702208-1
    # host: imlian.com
