# Basic
title: 苏联 | 探索无限
subtitle: An iOS Developer 
welcome_message: <a href="https://itunes.apple.com/us/app/晴子日语-自学日语的非凡搭档/id1173193999" target="_blank">Download my app</a>
description: Keep Discovering.
creator: <a href="http://imlian.com”>@lianshumin</a>

url: "http://imlian.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge 

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty. 
cover_color: blue
 
# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://itunes.apple.com/us/app/晴子日语-自学日语的非凡搭档/id1173193999'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: imlian
    # duoshuo: 
    
# Social
social:
    weibo: mrcccp
    github: lianshumin
    twitter: lianshumin
    gplus: 101698577363756110244
    mail: 3073303@qq.com

# Google Analytics
ga:
    # id: UA-74702208-1
    # host: imlian.com
